/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.tad_sebs.View;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import vn.tad_sebs.Model.Lop;
import vn.tad_sebs.Model.Student;
import vn.tad_sebs.View.ClassStat;

/**
 *
 * @author Sebs
 */
public class ClassView extends javax.swing.JFrame {

    /**
     * Creates new form ClassView
     */
    public ClassView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClassList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDClass = new javax.swing.JTextField();
        txtNameClass = new javax.swing.JTextField();
        txtSLClass = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoteClass = new javax.swing.JTextArea();
        btnAddClass = new javax.swing.JButton();
        btnEditClass = new javax.swing.JButton();
        btnDeleteClass = new javax.swing.JButton();
        btnClearClass = new javax.swing.JButton();
        btnSortbyIDClass = new javax.swing.JButton();
        btnSortbySLClass = new javax.swing.JButton();
        txtSubinClass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbListStudents = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cbChonlop = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtID1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPoint = new javax.swing.JTextField();
        btnUpdateCL = new javax.swing.JButton();
        btnClearCL = new javax.swing.JButton();
        btnSortbyIDCL = new javax.swing.JButton();
        btnSortbyNameCL = new javax.swing.JButton();
        btnSortbyPtsCL = new javax.swing.JButton();
        cbFind = new javax.swing.JComboBox<>();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        btnStat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbClassList.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "ID", "Tên lớp", "Số lượng học viên", "Ghi chú"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tbClassList.setShowGrid(false);
        tbClassList.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tbClassList);

        jLabel1.setText("ID");

        jLabel2.setText("Số lượng học viên");

        jLabel3.setText("Ghi chú");

        jLabel4.setText("Tên lớp");

        txtIDClass.setEnabled(false);

        txtNameClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameClassActionPerformed(evt);
            }
        });

        txtSLClass.setEnabled(false);

        txtNoteClass.setColumns(20);
        txtNoteClass.setRows(5);
        jScrollPane2.setViewportView(txtNoteClass);

        btnAddClass.setText("Thêm");

        btnEditClass.setText("Sửa");

        btnDeleteClass.setText("Xoá");

        btnClearClass.setText("Clear");

        btnSortbyIDClass.setText("Sắp xếp theo ID");

        btnSortbySLClass.setText("Sắp xếp theo Số lượng học viên");

        txtSubinClass.setEditable(false);
        txtSubinClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubinClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnSortbyIDClass)
                                                .addGap(110, 110, 110)
                                                .addComponent(btnSortbySLClass))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(46, 46, 46)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel2)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(txtSLClass,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        93,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel1)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(jLabel4))
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(70, 70, 70)
                                                                                                .addGroup(jPanel1Layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                txtIDClass,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                93,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(
                                                                                                                txtNameClass,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                401,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel1Layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addGap(69, 69,
                                                                                                                69)
                                                                                                        .addGroup(
                                                                                                                jPanel1Layout
                                                                                                                        .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addGroup(
                                                                                                                                jPanel1Layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                btnEditClass)
                                                                                                                                        .addGap(52,
                                                                                                                                                52,
                                                                                                                                                52)
                                                                                                                                        .addComponent(
                                                                                                                                                btnDeleteClass)
                                                                                                                                        .addGap(51,
                                                                                                                                                51,
                                                                                                                                                51)
                                                                                                                                        .addComponent(
                                                                                                                                                btnClearClass))
                                                                                                                        .addComponent(
                                                                                                                                jScrollPane2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                402,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                        .addComponent(btnAddClass)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(56, 56, 56)
                                                                .addComponent(txtSubinClass,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(130, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(txtIDClass,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtNameClass,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtSLClass,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 210,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnAddClass)
                                                        .addComponent(btnEditClass)
                                                        .addComponent(btnDeleteClass)
                                                        .addComponent(btnClearClass))
                                                .addGap(81, 81, 81)
                                                .addComponent(txtSubinClass, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSortbySLClass)
                                        .addComponent(btnSortbyIDClass))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Danh sách lớp học", jPanel1);

        tbListStudents.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "ID", "Họ và tên", "Giới tính", "Quê quán", "Điểm số"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.Float.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbListStudents);

        jLabel5.setText("Chọn lớp:");

        cbChonlop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChonlopActionPerformed(evt);
            }
        });

        jLabel6.setText("ID");

        txtID1.setEnabled(false);

        jLabel7.setText("Nhập điểm");

        txtPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPointActionPerformed(evt);
            }
        });

        btnUpdateCL.setText("Xác nhận");

        btnClearCL.setText("Clear");

        btnSortbyIDCL.setText("Sắp xếp theo ID");

        btnSortbyNameCL.setText("Sắp xếp theo Tên");
        btnSortbyNameCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortbyNameCLActionPerformed(evt);
            }
        });

        btnSortbyPtsCL.setText("Sắp xếp theo Điểm số");
        btnSortbyPtsCL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortbyPtsCLActionPerformed(evt);
            }
        });

        cbFind.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên", "Quê quán" }));

        btnFind.setText("Tìm kiếm");

        btnStat.setText("Thống kê điểm số theo lớp");
        btnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(44, 44, 44)
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(cbChonlop,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 386,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(34, 34, 34)
                                                                .addComponent(jScrollPane3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 817,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(40, 40, 40)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel2Layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                jLabel7)
                                                                                                        .addComponent(
                                                                                                                jLabel6))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel2Layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                txtID1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                96,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(
                                                                                                                txtPoint,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                293,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(cbFind,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(txtFind,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        178,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(
                                                                                                        btnFind))))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addGap(63, 63, 63)
                                                                                .addGroup(jPanel2Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                        .addComponent(btnStat,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        btnUpdateCL)
                                                                                                .addGap(125, 125, 125)
                                                                                                .addComponent(
                                                                                                        btnClearCL)))))))
                                                .addGap(0, 79, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnSortbyIDCL)
                                .addGap(50, 50, 50)
                                .addComponent(btnSortbyNameCL)
                                .addGap(55, 55, 55)
                                .addComponent(btnSortbyPtsCL)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbChonlop, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnSortbyIDCL)
                                                        .addComponent(btnSortbyNameCL)
                                                        .addComponent(btnSortbyPtsCL)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbFind, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnFind))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(txtPoint, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnUpdateCL)
                                                        .addComponent(btnClearCL))
                                                .addGap(102, 102, 102)
                                                .addComponent(btnStat, javax.swing.GroupLayout.PREFERRED_SIZE, 135,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(138, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Quản lý học viên từng lớp", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)));

        setSize(new java.awt.Dimension(1380, 775));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortbyPtsCLActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSortbyPtsCLActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSortbyPtsCLActionPerformed

    private void btnSortbyNameCLActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSortbyNameCLActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSortbyNameCLActionPerformed

    private void txtPointActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPointActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtPointActionPerformed

    private void cbChonlopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbChonlopActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cbChonlopActionPerformed

    private void txtSubinClassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSubinClassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSubinClassActionPerformed

    private void txtNameClassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNameClassActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNameClassActionPerformed

    private void btnStatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStatActionPerformed
        ClassStat classStat = new ClassStat();
        classStat.getTable(getTBListStudents());

        classStat.action();
    }// GEN-LAST:event_btnStatActionPerformed

    private void btnSortbyPtsCTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSortbyPtsCTActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSortbyPtsCTActionPerformed

    private void btnSortbyNameCTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSortbyNameCTActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnSortbyNameCTActionPerformed

    public void addAddClassListener(ActionListener listener) {
        btnAddClass.addActionListener(listener);
    }

    public void addEditClassListener(ActionListener listener) {
        btnEditClass.addActionListener(listener);
    }

    public void addDeleteClassListener(ActionListener listener) {
        btnDeleteClass.addActionListener(listener);
    }

    public void addClearClassListener(ActionListener listener) {
        btnClearClass.addActionListener(listener);
    }

    public void addSortClassbyIDListener(ActionListener listener) {
        btnSortbyIDClass.addActionListener(listener);
    }

    public void addSortClassbySLListener(ActionListener listener) {
        btnSortbySLClass.addActionListener(listener);
    }

    public void addCbChonlopListener(ActionListener listener) {
        cbChonlop.addActionListener(listener);
    }

    public void addFindStudentListener(ActionListener listener) {
        btnFind.addActionListener(listener);
    }

    public void addUpdateCLListener(ActionListener listener) {
        btnUpdateCL.addActionListener(listener);
    }

    public void addClearCLListener(ActionListener listener) {
        btnClearCL.addActionListener(listener);
    }

    public void addSortCLbyIDListener(ActionListener listener) {
        btnSortbyIDCL.addActionListener(listener);
    }

    public void addSortCLbyNameListener(ActionListener listener) {
        btnSortbyNameCL.addActionListener(listener);
    }

    public void addSortCLbyPtsListener(ActionListener listener) {
        btnSortbyPtsCL.addActionListener(listener);
    }

    public void addListTBClassSelectionListener(ListSelectionListener listener) {
        tbClassList.getSelectionModel().addListSelectionListener(listener);
    }

    public void addListTBStudentSelectionListener(ListSelectionListener listener) {
        tbListStudents.getSelectionModel().addListSelectionListener(listener);
    }

    public void addTabChangeListener(ChangeListener listener) {
        jTabbedPane1.addChangeListener(listener);
    }

    private String[] columnNamesClassList = new String[] {
            "ID", "Tên lớp", "Số lượng học viên", "Ghi chú"
    };

    public void showClassList(List<Lop> listLops) {
        int size = listLops.size();
        Object[][] data = new Object[size][4];

        for (int i = 0; i < size; i++) {
            data[i][0] = listLops.get(i).getId();
            data[i][1] = listLops.get(i).getName();
            data[i][2] = listLops.get(i).getIdStudent().size();
            data[i][3] = listLops.get(i).getNote();
        }

        tbClassList.setModel(new DefaultTableModel(data, columnNamesClassList));
    }

    private String[] columnNamesStudentList = new String[] {
            "ID", "Họ và tên", "Giới tính", "Quê quán", "Điểm số"
    };

    public Lop getLopInfo() {
        try {
            Lop lop = new Lop();
            if (txtIDClass.getText() != null && !"".equals(txtIDClass.getText())) {
                lop.setId(Integer.parseInt(txtIDClass.getText()));
            }

            lop.setName(txtNameClass.getText());
            lop.setNote(txtNoteClass.getText());
            if ("".equals(txtSLClass.getText())) {
                lop.setIdStudent(new ArrayList<>());
                lop.setIdMonhoc(new ArrayList<>());
            }

            return lop;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }

    public Student getStudentInfo() {
        try {
            Student student = new Student();

            student.setId(Integer.parseInt(txtID1.getText()));

            student.setDiem(Float.parseFloat(txtPoint.getText()));
            student.setName("");
            student.setGioitinh("");
            student.setAddress("");

            student.setLop(String.valueOf(getClassChoice()));
            student.setDate("");
            return student;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void clearClassInfo() {
        txtIDClass.setText("");
        txtNameClass.setText("");
        txtSLClass.setText("");
        txtNoteClass.setText("");
        // disable Edit and Delete buttons
        btnEditClass.setEnabled(false);
        btnDeleteClass.setEnabled(false);
        // enable Add button
        btnAddClass.setEnabled(true);
    }

    public void clearStudentInfo() {
        txtID1.setText("");
        txtPoint.setText("");
        // disable Edit and Delete buttons
        btnUpdateCL.setEnabled(false);
    }

    public void fillLopFromSelectedRow() {
        int row = tbClassList.getSelectedRow();
        if (row >= 0) {
            txtIDClass.setText(tbClassList.getValueAt(row, 0).toString());
            txtNameClass.setText(tbClassList.getValueAt(row, 1).toString());
            txtSLClass.setText(tbClassList.getValueAt(row, 2).toString());
            txtNoteClass.setText(tbClassList.getValueAt(row, 3).toString());
            // enable Edit and Delete buttons
            btnEditClass.setEnabled(true);
            btnDeleteClass.setEnabled(true);
            // disable Add button
            btnAddClass.setEnabled(false);

        }
    }

    public void fillStudentFromSelectedRow() {
        int row = tbListStudents.getSelectedRow();
        if (row >= 0) {
            txtID1.setText(tbListStudents.getValueAt(row, 0).toString());
            txtPoint.setText(tbListStudents.getValueAt(row, 4).toString());

            btnUpdateCL.setEnabled(true);
        }

    }

    public JComboBox getCbChonlop() {
        return cbChonlop;
    }

    public void resetforTab2() {

        txtID1.setText("");
        txtPoint.setText("");
        tbListStudents.clearSelection();
        btnUpdateCL.setEnabled(false);

    }

    public void resetforTab1() {
        txtIDClass.setText("");
        txtNameClass.setText("");
        txtSLClass.setText("");
        txtNoteClass.setText("");
        tbClassList.clearSelection();
        // disable Edit and Delete buttons
        btnEditClass.setEnabled(false);
        btnDeleteClass.setEnabled(false);
        // enable Add button
        btnAddClass.setEnabled(true);
    }

    public void showClassListinCbChonlop(List<Lop> listLops) {

        for (Lop lop : listLops) {
            cbChonlop.addItem(lop.getId() + " - " + lop.getName());
        }
    }

    public int getClassChoice() {

        String val = cbChonlop.getSelectedItem().toString();
        int index = val.indexOf(" - ");
        return Integer.parseInt(val.substring(0, index));

    }

    public void showStudentList(List<Student> listStudents) {
        int size = listStudents.size();
        Object[][] data = new Object[size][5];

        for (int i = 0; i < size; i++) {
            data[i][0] = listStudents.get(i).getId();
            data[i][1] = listStudents.get(i).getName();
            data[i][2] = listStudents.get(i).getGioitinh();
            data[i][3] = listStudents.get(i).getAddress();
            data[i][4] = listStudents.get(i).getDiem();
        }

        tbListStudents.setModel(new DefaultTableModel(data, columnNamesStudentList));
    }

    public void showListCl(List<Lop> list) {
        int size = list.size();
        Object[][] data = new Object[size][5];
        for (int i = 0; i < size; i++) {
            cbChonlop.addItem(list.get(i).getId() + " - " + list.get(i).getName());
        }

    }

    public TableModel getTBListStudents() {
        // Get the original table model
        TableModel originalModel = tbListStudents.getModel();

        // Create a new table model for the score distribution
        DefaultTableModel distributionModel = new DefaultTableModel(new Object[] { "Range", "Count" }, 0);

        // Create an array to count the score distribution
        int[] distribution = new int[10];

        // Count the score distribution
        for (int i = 0; i < originalModel.getRowCount(); i++) {
            float score = Float.parseFloat(originalModel.getValueAt(i, 4).toString()); // replace 4 with the column
                                                                                       // index for the score
            int index = Math.min((int) score, 9);
            distribution[index]++;
        }

        // Add the distribution to the new table model
        for (int i = 0; i < 10; i++) {
            distributionModel.addRow(new Object[] { i + "-" + (i + 1), distribution[i] });
        }

        return distributionModel;
    }

    public String getSearchBoxStudent() {
        return txtFind.getText().trim();
    }

    public int getCriteria() {
        return cbFind.getSelectedIndex();
    }

    public int getStudentID() {
        return Integer.parseInt(txtID1.getText());
    }

    public int getLopID() {
        return Integer.parseInt(txtIDClass.getText());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddClass;
    private javax.swing.JButton btnClearCL;
    private javax.swing.JButton btnClearClass;
    private javax.swing.JButton btnDeleteClass;
    private javax.swing.JButton btnEditClass;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSortbyIDCL;
    private javax.swing.JButton btnSortbyIDClass;
    private javax.swing.JButton btnSortbyNameCL;
    private javax.swing.JButton btnSortbyPtsCL;
    private javax.swing.JButton btnSortbySLClass;
    private javax.swing.JButton btnStat;
    private javax.swing.JButton btnUpdateCL;
    private javax.swing.JComboBox<String> cbChonlop;
    private javax.swing.JComboBox<String> cbFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbClassList;
    private javax.swing.JTable tbListStudents;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtIDClass;
    private javax.swing.JTextField txtNameClass;
    private javax.swing.JTextArea txtNoteClass;
    private javax.swing.JTextField txtPoint;
    private javax.swing.JTextField txtSLClass;
    private javax.swing.JTextField txtSubinClass;
    // End of variables declaration//GEN-END:variables
}
