/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.tad_sebs.View;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import vn.tad_sebs.Model.Exam;

/**
 *
 * @author ASUS
 */
public class ExamView extends javax.swing.JFrame {

    /**
     * Creates new form ExamView
     */
    public ExamView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        Examtable = new javax.swing.JTable();
        FIDSearchExam = new javax.swing.JTextField();
        FNameSearchExam = new javax.swing.JTextField();
        FTeacherSearchExam = new javax.swing.JTextField();
        FSearchTime = new com.toedter.calendar.JDateChooser();
        btnAddExam = new javax.swing.JButton();
        btnDeleteExam = new javax.swing.JButton();
        btnEditExam = new javax.swing.JButton();
        btnClearExam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CbbSearchExam = new javax.swing.JComboBox<>();
        btnEditTeacher = new javax.swing.JButton();
        btnSortbyIDExam = new javax.swing.JButton();
        btnSortbyTime = new javax.swing.JButton();
        FSearchExam = new javax.swing.JTextField();
        btnSearchExam = new javax.swing.JButton();
        panelTeacher = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListPush = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        LishPull = new javax.swing.JList<>();
        btnPush = new javax.swing.JButton();
        btnPull = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Examtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên kỳ thi", "Thời gian", "Giám thị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Examtable);

        btnAddExam.setText("Thêm");

        btnDeleteExam.setText("Xóa");

        btnEditExam.setText("Chỉnh sửa");

        btnClearExam.setText("Clear");

        jLabel1.setText("ID");

        jLabel2.setText("Tên kỳ thi");

        jLabel3.setText("Giám thị");

        jLabel4.setText("Thời gian");

        CbbSearchExam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên", "Thời gian" }));

        btnEditTeacher.setText("Chỉnh sửa");

        btnSortbyIDExam.setText("Sort by ID");

        btnSortbyTime.setText("Sort by Time");

        btnSearchExam.setText("Tìm");

        panelTeacher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListPush.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(ListPush);

        LishPull.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(LishPull);

        btnPush.setText(">>");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnPull.setText("<<");

        jLabel6.setText("Giám thị ");

        jLabel7.setText("Giám thị đã được chọn");

        javax.swing.GroupLayout panelTeacherLayout = new javax.swing.GroupLayout(panelTeacher);
        panelTeacher.setLayout(panelTeacherLayout);
        panelTeacherLayout.setHorizontalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(btnPull, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTeacherLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPush, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
        );
        panelTeacherLayout.setVerticalGroup(
            panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
            .addGroup(panelTeacherLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btnPush)
                .addGap(33, 33, 33)
                .addComponent(btnPull)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(CbbSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchExam))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnSortbyIDExam)
                                .addGap(53, 53, 53)
                                .addComponent(btnSortbyTime)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FSearchTime, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FIDSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FNameSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FTeacherSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddExam)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeleteExam)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditExam)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearExam))
                            .addComponent(panelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbbSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchExam))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FIDSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FNameSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FTeacherSearchExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnEditTeacher))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FSearchTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddExam)
                            .addComponent(btnDeleteExam)
                            .addComponent(btnEditExam)
                            .addComponent(btnClearExam))
                        .addGap(18, 18, 18)
                        .addComponent(panelTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortbyIDExam)
                    .addComponent(btnSortbyTime))
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String[] columnNamesExam = new String[] {
            "ID", "Tên kỳ thi", "Thời gian", "Giám thị"};
    public void showListExam(List<Exam> list) {
        int size = list.size();
        Object[][] exam = new Object[size][4];
        for (int i = 0; i < size; i++) {
            exam[i][0] = list.get(i).getId();
            exam[i][1] = list.get(i).getName();
            exam[i][2] = list.get(i).getTime();
            exam[i][3] = list.get(i).getGiamthi();
        }
       Examtable.setModel(new DefaultTableModel(exam, columnNamesExam));
    }
    public void fillExamFromSelectedRow() {
        // lấy chỉ số của hàng được chọn
        int row = Examtable.getSelectedRow();
        if (row >= 0) {
            FIDSearchExam.setText(Examtable.getModel().getValueAt(row, 0).toString());
            FNameSearchExam.setText(Examtable.getModel().getValueAt(row, 1).toString());
            FTeacherSearchExam.setText(Examtable.getModel().getValueAt(row, 2).toString());
            String dateString = Examtable.getModel().getValueAt(row, 2).toString(); // Chuỗi ngày tháng cần chuyển đổi
            JDateChooser dateChooser = new JDateChooser();
        
        // Định dạng của chuỗi ngày tháng
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);
            
            // Thiết lập ngày cho JDateChooser
            FSearchTime.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
            // enable Edit and Delete buttons
            btnEditExam.setEnabled(true);
            btnDeleteExam.setEnabled(true);
            btnEditTeacher.setEnabled(true);
            // disable Add button
            btnAddExam.setEnabled(false);
        }
    }
    public void showExam(Exam exam)
    {
        FIDSearchExam.setText(String.valueOf(exam.getId()));
        FNameSearchExam.setText(exam.getName());
        FTeacherSearchExam.setText(String.valueOf(exam.getGiamthi()));
        String dateString = exam.getTime();
            JDateChooser dateChooser = new JDateChooser();
        
        // Định dạng của chuỗi ngày tháng
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);
            
            // Thiết lập ngày cho JDateChooser
            FSearchTime.setDate(date);

        //enable Delete and edit button
        btnEditExam.setEnabled(true);
        btnDeleteExam.setEnabled(true);
        btnEditTeacher.setEnabled(true);
        //disable Add button
        btnAddExam.setEnabled(false);
    }   catch (ParseException ex) {
            Logger.getLogger(ExamView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        public void clearExamInfo() 
        {
        FIDSearchExam.setText("");
        FNameSearchExam.setText("");
        FTeacherSearchExam.setText("");
        String dateString = "01/01/1111"; // Chuỗi ngày tháng cần chuyển đổi
            JDateChooser dateChooser = new JDateChooser();
        
        // Định dạng của chuỗi ngày tháng
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);
            
            // Thiết lập ngày cho JDateChooser
            FSearchTime.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();    
        }

        // disable Edit and Delete buttons
        btnEditExam.setEnabled(false);
        btnDeleteExam.setEnabled(false);
        btnEditTeacher.setEnabled(true);
        // enable Add button
        btnAddExam.setEnabled(true);
    }
        public Exam getExamInfo()
    {
        try
        {
            
            Exam exam = new Exam();
            if(FIDSearchExam.getText()!=null && !"".equals(FIDSearchExam.getText()))
            {
                exam.setId(Integer.parseInt(FIDSearchExam.getText()));
            }

            exam.setName(FNameSearchExam.getText());
            exam.setGiamthi(Integer.parseInt(FTeacherSearchExam.getText()));
            exam.setTime(FSearchTime.getDateFormatString());
            
            return exam;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
        
    }
    public void addAddExamListener(ActionListener listener) {
        btnAddExam.addActionListener(listener);
    }

    public void addEditExamListener(ActionListener listener) {
        btnEditExam.addActionListener(listener);
    }

    public void addDeleteExamListener(ActionListener listener) {
        btnDeleteExam.addActionListener(listener);
    }

    public void addClearExamListener(ActionListener listener) {
        btnClearExam.addActionListener(listener);
    }

    public void addListExamSelectionListener(ListSelectionListener listener) {
        Examtable.getSelectionModel().addListSelectionListener(listener);
    }

    public void addSearchExamListener(ActionListener listener) {
        btnSearchExam.addActionListener(listener);
    }
    public void addSortExamByIDListener(ActionListener listener)
    {
        btnSortbyIDExam.addActionListener(listener);
    }
    public void addSortStudentByTimeListener(ActionListener listener)
    {
        btnSortbyTime.addActionListener(listener);
    }
    public void addEditTeacherListener(ActionListener listener)
    {
        btnEditTeacher.addActionListener(listener);
    }
    public void addPushListener(ActionListener listener)
    {
        btnPush.addActionListener(listener);
    }
    public void addPullListener(ActionListener listener)
    {
        btnPull.addActionListener(listener);
    }
    
    public String getSelectedTextExam() {
        return CbbSearchExam.getSelectedItem().toString();
    }
    
    public String getSearchBoxExam()
    {
        return FSearchExam.getText().trim();
    }
    

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }    
        

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPushActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbSearchExam;
    private javax.swing.JTable Examtable;
    private javax.swing.JTextField FIDSearchExam;
    private javax.swing.JTextField FNameSearchExam;
    private javax.swing.JTextField FSearchExam;
    private com.toedter.calendar.JDateChooser FSearchTime;
    private javax.swing.JTextField FTeacherSearchExam;
    private javax.swing.JList<String> LishPull;
    private javax.swing.JList<String> ListPush;
    private javax.swing.JButton btnAddExam;
    private javax.swing.JButton btnClearExam;
    private javax.swing.JButton btnDeleteExam;
    private javax.swing.JButton btnEditExam;
    private javax.swing.JButton btnEditTeacher;
    private javax.swing.JButton btnPull;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnSearchExam;
    private javax.swing.JButton btnSortbyIDExam;
    private javax.swing.JButton btnSortbyTime;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelTeacher;
    // End of variables declaration//GEN-END:variables
}
