/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.tad_sebs.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ASUS
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        QLHV = new javax.swing.JButton();
        QLLH = new javax.swing.JButton();
        QLCBGV = new javax.swing.JButton();
        QLCTH = new javax.swing.JButton();
        QLKT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        QLTL = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QLHV.setText("Quản lý học viên");
        
        QLLH.setText("quản lý lớp học ");
        
        QLCBGV.setText("quản lý cán bộ giáo viên");
        

        QLCTH.setText("Quản lý môn học");

        QLKT.setText("quản lý kì thi");
        
        jLabel1.setText("Các Ffame khác");

        QLTL.setText("Quản lý tài liệu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLHV)
                    .addComponent(QLLH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QLCBGV, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(QLCTH, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(QLKT)
                        .addGap(30, 30, 30)
                        .addComponent(QLTL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLHV)
                    .addComponent(QLCTH))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLKT)
                    .addComponent(QLTL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QLCBGV)
                    .addComponent(QLLH))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void addQLHVListener(ActionListener listener) {      
        QLHV.addActionListener(listener);
        
    }
    public void addQLCTHListener(ActionListener listener) {
        QLCTH.addActionListener(listener);
    }
    public void addQLLHListener(ActionListener listener) {
        QLLH.addActionListener(listener);
    }
    public void addQLKTListener(ActionListener listener) {
        QLKT.addActionListener(listener);
    }
    public void addQLCBGVListener(ActionListener listener) {
        QLCBGV.addActionListener(listener);
    }
    public void addQLTLListener(ActionListener listener)
    {
        QLTL.addActionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QLCBGV;
    private javax.swing.JButton QLCTH;
    private javax.swing.JButton QLHV;
    private javax.swing.JButton QLKT;
    private javax.swing.JButton QLLH;
    private javax.swing.JButton QLTL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
