/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.tad_sebs.View;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JDialog;

import vn.tad_sebs.Model.Lop;
import vn.tad_sebs.Model.Student;
import vn.tad_sebs.DAO.LopDAO;

/**
 *
 * @author Sebs
 */
public class StudentCustomSearch extends javax.swing.JPanel {

    private LopDAO lopDao;
    private JDialog dialog;

    /**
     * Creates new form StudentCustomSearch
     */
    public StudentCustomSearch() {
        initComponents();
        lopDao = new LopDAO();
        List<Lop> lopList = lopDao.getListLops();
        ArrayList<String> lopNameList = new ArrayList<>();
        for (Lop l : lopList) {
            lopNameList.add(l.getId() + " - " + l.getName());
        }
        showListLop(lopNameList);

    }

    public void doDialog() {
        dialog = new JDialog();
        dialog.setTitle("Tìm kiếm theo nhiều tiêu chí");
        dialog.setResizable(false);
        dialog.setContentPane(this);
        dialog.setSize(478, 375);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        // Đặt vị trí của JDialog ở góc dưới cùng bên trái trên thanh taskbar
        dialog.setLocation(0, screenSize.height - dialog.getHeight() - 40);

        dialog.setVisible(true);
        

    }

    public void dispose()
    {
        dialog.dispose();
    }

    private List<Student> listStudents;

    public interface OnOkButtonClickListener {
        void onOkButtonClick(List<Student> students);
    }

    private OnOkButtonClickListener listener;

    public void setOnOkButtonClickListener(OnOkButtonClickListener listener) {
        this.listener = listener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        cbLop = new javax.swing.JComboBox<>();
        txtDateFrom = new com.toedter.calendar.JDateChooser();
        chkName = new javax.swing.JCheckBox();
        chkDate = new javax.swing.JCheckBox();
        chkAddress = new javax.swing.JCheckBox();
        chkSex = new javax.swing.JCheckBox();
        chkLop = new javax.swing.JCheckBox();
        chkM = new javax.swing.JRadioButton();
        chkF = new javax.swing.JRadioButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtDateTo = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setBackground(new java.awt.Color(155, 253, 155));
        setMinimumSize(new java.awt.Dimension(478, 349));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAddress.setEnabled(false);

        cbLop.setEnabled(false);

        txtDateFrom.setDateFormatString("dd/MM/yyyy");
        txtDateFrom.setEnabled(false);

        chkName.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        chkName.setForeground(new java.awt.Color(42, 147, 177));
        chkName.setSelected(true);
        chkName.setText("Tên");
        chkName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNameActionPerformed(evt);
            }
        });

        chkDate.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        chkDate.setForeground(new java.awt.Color(42, 147, 177));
        chkDate.setText("Ngày sinh");
        chkDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDateActionPerformed(evt);
            }
        });

        chkAddress.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        chkAddress.setForeground(new java.awt.Color(42, 147, 177));
        chkAddress.setText("Quê quán");
        chkAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAddressActionPerformed(evt);
            }
        });

        chkSex.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        chkSex.setForeground(new java.awt.Color(42, 147, 177));
        chkSex.setText("Giới tính");
        chkSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSexActionPerformed(evt);
            }
        });

        chkLop.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        chkLop.setForeground(new java.awt.Color(42, 147, 177));
        chkLop.setText("Lớp");
        chkLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLopActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkM);
        chkM.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        chkM.setForeground(new java.awt.Color(42, 147, 177));
        chkM.setText("Nam");
        chkM.setEnabled(false);
        chkM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkF);
        chkF.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        chkF.setForeground(new java.awt.Color(42, 147, 177));
        chkF.setText("Nữ");
        chkF.setEnabled(false);

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/check.png"))); // NOI18N
        btnOK.setText("Xác nhận");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/Delete.png"))); // NOI18N
        btnCancel.setText("Huỷ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtDateTo.setDateFormatString("dd/MM/yyyy");
        txtDateTo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 147, 177));
        jLabel5.setText("Từ");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 147, 177));
        jLabel6.setText("Đến");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(chkSex)
                                                                        .addComponent(chkAddress)
                                                                        .addComponent(chkLop))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(txtAddress)
                                                                                .addComponent(cbLop,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        255,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(chkM)
                                                                                .addGap(76, 76, 76)
                                                                                .addComponent(chkF))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(100, 100, 100)
                                                                .addComponent(btnOK)
                                                                .addGap(56, 56, 56)
                                                                .addComponent(btnCancel)))
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(chkDate)
                                                        .addComponent(chkName,
                                                                javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtName)
                                                                .addGap(19, 19, 19))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtDateFrom,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        63, Short.MAX_VALUE)
                                                                .addComponent(txtDateTo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 80,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(74, 74, 74)))))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkName)
                                                .addGap(33, 33, 33)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(chkDate)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDateFrom, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDateTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkF)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbLop, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(chkSex)
                                                        .addComponent(chkM))
                                                .addGap(18, 18, 18)
                                                .addComponent(chkAddress)
                                                .addGap(18, 18, 18)
                                                .addComponent(chkLop)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnOK)
                                        .addComponent(btnCancel))
                                .addGap(38, 38, 38)));
    }// </editor-fold>//GEN-END:initComponents

    private void chkNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkNameActionPerformed
        if (chkName.isSelected()) {
            txtName.setEnabled(true);
        } else
            txtName.setEnabled(false);
    }// GEN-LAST:event_chkNameActionPerformed

    private void chkDateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkDateActionPerformed
        if (chkDate.isSelected()) {
            txtDateFrom.setEnabled(true);
            txtDateTo.setEnabled(true);
        } else {
            txtDateFrom.setEnabled(false);
            txtDateTo.setEnabled(false);
        }
    }// GEN-LAST:event_chkDateActionPerformed

    private void chkSexActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkSexActionPerformed
        if (chkSex.isSelected()) {
            chkM.setEnabled(true);
            chkF.setEnabled(true);
        } else {
            chkM.setEnabled(false);
            chkF.setEnabled(false);
        }
    }// GEN-LAST:event_chkSexActionPerformed

    private void chkAddressActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkAddressActionPerformed
        if (chkAddress.isSelected()) {
            txtAddress.setEnabled(true);
        } else
            txtAddress.setEnabled(false);
    }// GEN-LAST:event_chkAddressActionPerformed

    private void chkLopActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkLopActionPerformed
        if (chkLop.isSelected()) {
            cbLop.setEnabled(true);
        } else
            cbLop.setEnabled(false);
    }// GEN-LAST:event_chkLopActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCancelActionPerformed
        dialog.dispose();
    }// GEN-LAST:event_btnCancelActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNameActionPerformed

    private void chkMActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkMActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chkMActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnOKActionPerformed
        if (listener != null) {
            List<Student> students = getSearchData();
            listener.onOkButtonClick(students);
        }
    }// GEN-LAST:event_btnOKActionPerformed

    public void showListLop(ArrayList<String> list) {
        for (String item : list) {
            cbLop.addItem(item);
        }
    }

    public List<Student> getSearchData() {
        String name = txtName.getText();
        String address = txtAddress.getText();
        // Seperate lop id from lop name
        String lop = cbLop.getSelectedItem().toString().split(" - ")[0];
        Date dateFrom = txtDateFrom.getDate();
        Date dateTo = txtDateTo.getDate();
        String sex = chkM.isSelected() ? "Nam" : "Nữ";

        boolean isName = chkName.isSelected();
        boolean isAddress = chkAddress.isSelected();
        boolean isLop = chkLop.isSelected();
        boolean isDate = chkDate.isSelected();
        boolean isSex = chkSex.isSelected();

        List<Student> list = listStudents;
        if (isName) {
            list = listStudents.stream().filter(s -> s.getName().toLowerCase().contains(name.toLowerCase())).toList();
        }
        if (isAddress) {
            list = list.stream().filter(s -> s.getAddress().toLowerCase().contains(address.toLowerCase())).toList();
        }
        if (isLop) {
            list = list.stream().filter(s -> s.getLop().contains(lop)).toList();
        }
        if (isDate) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            list = list.stream().filter(s -> {
                try {
                    return dateFormat.parse(s.getDate()).after(dateFrom)
                            && dateFormat.parse(s.getDate()).before(dateTo);
                } catch (ParseException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                return false;
            }).toList();
        }

        if (isSex) {
            list = list.stream().filter(s -> s.getGioitinh().equals(sex)).toList();
        }

        return list;

    }

    public void getListStudents(List<Student> listStudents) {
        this.listStudents = listStudents;
    }

    public void clear() throws ParseException {
        txtName.setText("");
        txtAddress.setText("");
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtDateFrom.setDate(dateFormat.parse("01/01/2024"));
        txtDateTo.setDate(dateFormat.parse("01/01/2024"));
        chkM.setSelected(true);
        cbLop.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbLop;
    private javax.swing.JCheckBox chkAddress;
    private javax.swing.JCheckBox chkDate;
    private javax.swing.JRadioButton chkF;
    private javax.swing.JCheckBox chkLop;
    private javax.swing.JRadioButton chkM;
    private javax.swing.JCheckBox chkName;
    private javax.swing.JCheckBox chkSex;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAddress;
    private com.toedter.calendar.JDateChooser txtDateFrom;
    private com.toedter.calendar.JDateChooser txtDateTo;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
