/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.tad_sebs.View;

import javax.swing.*;
import com.toedter.calendar.JDateChooser;

import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import vn.tad_sebs.Model.CourseFeeEntry;
import vn.tad_sebs.Model.CourseTeacherEntry;
import vn.tad_sebs.Model.Entry;
import vn.tad_sebs.Model.Lop;
import vn.tad_sebs.Model.Monhoc;
import vn.tad_sebs.Model.Student;
import vn.tad_sebs.Model.Teacher;
import vn.tad_sebs.View.MainView;
import vn.tad_sebs.Controller.MainController;

import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.forms.PdfAcroForm;
import com.itextpdf.forms.fields.PdfFormField;
import java.awt.event.ActionEvent;

import java.io.IOException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import vn.tad_sebs.Controller.LoginController;
import vn.tad_sebs.Controller.MainController2;
import vn.tad_sebs.Model.User;

/**
 *
 * @author ASUS
 */
public class StudentView2 extends javax.swing.JFrame {

  
    public StudentView2() {
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        chkMStep3.setSelected(true);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                MainView2 mainView2 = new MainView2();
                MainController2 mainController2 = new MainController2(mainView2);
                mainController2.showMainView2();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Step1 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Step2 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbPackageListStep2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listInv = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listChoose = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnPull = new javax.swing.JButton();
        btnPush = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Step3 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMonhoc = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnAddStudent = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPackageList = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGVSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbSelectedGV = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Step4 = new javax.swing.JLayeredPane();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listMonhoc1 = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        FAddressSearchStudentStep4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        chkFStep4 = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        FDateSearchStudentStep4 = new com.toedter.calendar.JDateChooser();
        BtnAddStudent1 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbPackageList1 = new javax.swing.JTable();
        chkMStep4 = new javax.swing.JCheckBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnGVSave1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        FNameSearchStudentStep4 = new javax.swing.JTextField();
        FIDSearchStudentStep4 = new javax.swing.JTextField();
        cbSelectedGV1 = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ HỌC VIÊN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(icon.getImage());
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Step1.setPreferredSize(new java.awt.Dimension(1240, 740));
        Step1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Họ và tên");
        Step1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        jLabel14.setText("Ngày sinh");
        Step1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        jLabel15.setText("Giới tính");
        Step1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jLabel16.setText("Quê quán");
        Step1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Step1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 240, -1));
        Step1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, 250, -1));

        jCheckBox2.setText("Nam");
        Step1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        jCheckBox3.setText("Nữ");
        Step1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));
        Step1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        jButton2.setText("Tiếp tục");
        Step1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 713, 90, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 255, 73));
        jLabel18.setText("ĐĂNG KÝ THÔNG TIN HỌC VIÊN MỚI");
        Step1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel20.setText("ĐĂNG KÝ THÔNG TIN CÁ NHÂN");
        Step1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/QLHV2.png"))); // NOI18N
        Step1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        getContentPane().add(Step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        Step2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPackageListStep2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên khóa", "Chi phí", "Giáo viên"
            }
        ));
        jScrollPane4.setViewportView(tbPackageListStep2);

        Step2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 300, 250));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 73));
        jLabel7.setText("ĐĂNG KÝ THÔNG TIN HỌC VIÊN MỚI");
        Step2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 255, 73));
        jLabel19.setText("Khoá học đã đăng ký");
        Step2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 190, -1));

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel21.setText("ĐĂNG KÝ KHÓA HỌC");
        Step2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        listInv.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listInv);

        Step2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, 260));

        listChoose.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(listChoose);

        Step2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 140, 250));

        jLabel22.setText("KHÓA HỌC HIỆN CÓ");
        Step2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel23.setText("KHÓA HỌC ĐÃ CHỌN");
        Step2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        btnPull.setText("<<");
        Step2.add(btnPull, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 60, 20));

        btnPush.setText(">>");
        Step2.add(btnPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 60, 20));

        btnCheck.setText("Xác nhận");
        Step2.add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/QLHV2.png"))); // NOI18N
        Step2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        getContentPane().add(Step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        Step3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 73));
        jLabel3.setText("KIỂM TRA LẠI THÔNG TIN !!!");
        Step3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, 30));

        listMonhoc.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listMonhoc);

        Step3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 110, 160));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 73));
        jLabel1.setText("ĐĂNG KÝ THÔNG TIN HỌC VIÊN MỚI");
        Step3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 73));
        jLabel13.setText("Giáo viên được chọn");
        Step3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 190, -1));

        BtnAddStudent.setText("Thêm");
        Step3.add(BtnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 110, 30));

        tbPackageList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbPackageList);

        Step3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 410, 320));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 73));
        jLabel11.setText("Khoá học đã đăng ký");
        Step3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 73));
        jLabel5.setText("-->");
        Step3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 30, -1));

        btnGVSave.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGVSave.setText("Lưu");
        btnGVSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGVSaveActionPerformed(evt);
            }
        });
        Step3.add(btnGVSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, -1, -1));

        jButton1.setText("Trở lại");
        Step3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, 30));

        cbSelectedGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Step3.add(cbSelectedGV, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 140, 70));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane7.setViewportView(jTextArea1);

        Step3.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 200, -1, 250));

        jLabel24.setText("THÊM GIÁO VIÊN VÀ KIỂM TRA LẠI THÔNG TIN");
        Step3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/QLHV2.png"))); // NOI18N
        Step3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1260, 750));

        getContentPane().add(Step3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        Step4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 225, 73));
        jLabel26.setText("ID");
        Step4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 30, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 255, 73));
        jLabel27.setText("KIỂM TRA LẠI THÔNG TIN !!!");
        Step4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, -1, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 255, 73));
        jLabel28.setText("Ngày sinh");
        Step4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, -1));

        listMonhoc1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listMonhoc1);

        Step4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 110, 160));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 255, 73));
        jLabel29.setText("Giới tính");
        Step4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, -1));

        FAddressSearchStudentStep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAddressSearchStudentStep4ActionPerformed(evt);
            }
        });
        Step4.add(FAddressSearchStudentStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 163, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 255, 73));
        jLabel30.setText("Quê quán");
        Step4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 80, -1));

        btnGroup.add(chkFStep4);
        chkFStep4.setForeground(new java.awt.Color(255, 255, 255));
        chkFStep4.setText("Nữ");
        Step4.add(chkFStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 70, -1));

        jLabel31.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 255, 73));
        jLabel31.setText("ĐĂNG KÝ THÔNG TIN HỌC VIÊN MỚI");
        Step4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 255, 73));
        jLabel32.setText("Giáo viên được chọn");
        Step4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 190, -1));

        FDateSearchStudentStep4.setDateFormatString("dd/MM/yyyy");
        Step4.add(FDateSearchStudentStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 163, -1));

        BtnAddStudent1.setText("Thêm");
        Step4.add(BtnAddStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 110, 30));

        tbPackageList1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbPackageList1);

        Step4.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 280, 250));

        btnGroup.add(chkMStep4);
        chkMStep4.setForeground(new java.awt.Color(255, 255, 255));
        chkMStep4.setText("Nam");
        Step4.add(chkMStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 80, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 255, 73));
        jLabel33.setText("Khoá học đã đăng ký");
        Step4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 190, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 255, 73));
        jLabel34.setText("-->");
        Step4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 30, -1));

        btnGVSave1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnGVSave1.setText("Lưu");
        btnGVSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGVSave1ActionPerformed(evt);
            }
        });
        Step4.add(btnGVSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, -1, -1));

        jButton3.setText("Trở lại");
        Step4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, -1, 30));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 255, 73));
        jLabel35.setText("Họ và tên");
        Step4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));
        Step4.add(FNameSearchStudentStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 163, 22));

        FIDSearchStudentStep4.setEnabled(false);
        FIDSearchStudentStep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDSearchStudentStep4ActionPerformed(evt);
            }
        });
        Step4.add(FIDSearchStudentStep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 80, -1));

        cbSelectedGV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Step4.add(cbSelectedGV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 140, 70));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane9.setViewportView(jTextArea2);

        Step4.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, -1, 250));

        jLabel36.setText("THÊM GIÁO VIÊN VÀ KIỂM TRA LẠI THÔNG TIN");
        Step4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/tad_sebs/icon/QLHV2.png"))); // NOI18N
        Step4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1240, 740));

        getContentPane().add(Step4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void FAddressSearchStudentStep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAddressSearchStudentStep4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAddressSearchStudentStep4ActionPerformed

    private void btnGVSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGVSave1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGVSave1ActionPerformed

    private void FIDSearchStudentStep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDSearchStudentStep4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDSearchStudentStep4ActionPerformed

    private void btnGVSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGVSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGVSaveActionPerformed

    public int editingPackage;

    private void btnGVSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnGVSaveActionPerformed
        // lưu thông tin vào courseTeacherMap
        int idTeacher = Integer.parseInt(cbSelectedGV.getSelectedItem().toString().split(" - ")[0]);
        int idMonhoc = Integer.parseInt(listMonhoc.getSelectedValue().split(" - ")[0]);
        System.out.println(editingPackage);
        
        for (CourseTeacherEntry entry : courseTeacherMap) {
            if (entry.getCourseId() == editingPackage) {
                for (Entry teacherEntry : entry.getTeacherMap()) {
                    if (teacherEntry.getIdMonhoc() == idMonhoc) {
                        teacherEntry.setIdTeacher(idTeacher);
                        break;
                    }
                }
            }
        }

    }// GEN-LAST:event_btnGVSaveActionPerformed

    ImageIcon icon = new ImageIcon((getClass().getResource("/vn/tad_sebs/icon/icon.png")));

    private List<Teacher> listTeacher = new ArrayList<>();

    public void getListTeachers(List<Teacher> list) {
        listTeacher = list;
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Teacher teacher : listTeacher) {
            model.addElement(teacher.getId() + " - " + teacher.getName());
        }
        cbSelectedGV.setModel(model);
    }

    private void BtnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnAddStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnAddStudentActionPerformed

    private void BtnClearStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnClearStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnClearStudentActionPerformed

    private void BtnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnEditStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnEditStudentActionPerformed

    private void BtnSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BtnSearchStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_BtnSearchStudentActionPerformed

    private void chkFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chkFActionPerformed

    private void FIDSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FIDSearchStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_FIDSearchStudentActionPerformed
    private void FAddressSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FAddressSearchStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_FAddressSearchStudentActionPerformed

    private void FTeacherSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FTeacherSearchStudentActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_FTeacherSearchStudentActionPerformed
        
    private List<Lop> listLop = new ArrayList<>();

    public void getListLops(List<Lop> list) {
        listLop = list;
    }

    private String[] columnPackageNames = new String[] {
            "ID", "Tên khoá", "Chi phí","Giáo viên" };

    private List<Monhoc> listSubs = new ArrayList<>();

    public void getListSubjects(List<Monhoc> list) {
        listSubs = list;
    }

    public void showSubjects(List<Entry> list) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Entry entry : list) {
            for (Monhoc monhoc : listSubs) {
                if (monhoc.getId() == entry.getIdMonhoc()) {
                    model.addElement(entry.getIdMonhoc() + " - " + monhoc.getName());
                    break;
                }
            }
            
        }
        listMonhoc.setModel(model);
    }

    private List<Integer> editingLop;
    private List<CourseTeacherEntry> courseTeacherMap = new ArrayList<>();

    public void showStudent(Student student) {
        FIDSearchStudentStep3.setText(String.valueOf(student.getId()));
        FNameSearchStudentStep3.setText(student.getName());

        String dateString = student.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);

            // Thiết lập ngày cho JDateChooser
            FDateSearchStudentStep3.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        editingLop = student.getLop();
        courseTeacherMap = student.getCourseTeacherMap();
        if (student.getGioitinh().equals("Nam")) {
            chkMStep3.setSelected(true);
        } else
            chkFStep3.setSelected(true);
        FAddressSearchStudentStep3.setText(student.getAddress());

        List<CourseFeeEntry> courseFeeMap = student.getCourseFeeMap();

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnPackageNames);

        for (CourseFeeEntry entry : courseFeeMap) {
            for (Lop lop : listLop) {
                if (lop.getId() == entry.getCourseId()) {
                    model.addRow(new Object[] {
                            lop.getId(), lop.getName(), entry.getFee() == false ? "Chưa đóng" : "Đã đóng"
                    });
                    break;
                }
            }

        }
        tbPackageList.setModel(model);

        //print out the courseTeacherMap
        for (CourseTeacherEntry entry : courseTeacherMap) {
            System.out.println("Course ID: " + entry.getCourseId());
            for (Entry teacherEntry : entry.getTeacherMap()) {
                System.out.println("Subject ID: " + teacherEntry.getIdMonhoc() + " - Teacher ID: " + teacherEntry.getIdTeacher());
            }
        }
            FNameSearchStudentStep3.setEnabled(false);
            FDateSearchStudentStep3.setEnabled(false);
            chkMStep3.setEnabled(false);
            chkFStep3.setEnabled(false);
            FAddressSearchStudentStep3.setEnabled(false);
            BtnAddStudent.setEnabled(false);
        // enable Delete and edit button

    }

    public void addListPackageSelectionListener(ListSelectionListener listener) {
        tbPackageList.getSelectionModel().addListSelectionListener(listener);
    }

    public void addAddStudentListener(ActionListener listener) {
        BtnAddStudent.addActionListener(listener);
    }
    public void addConfirmListener(ActionListener listener) {
        btnCheck.addActionListener(listener);
    }

    public void addListMonhocSelectionListener(ListSelectionListener listener) {
        listMonhoc.addListSelectionListener(listener);
    }

    public int getSelectedPackage() {
        return Integer.parseInt(tbPackageList.getValueAt(tbPackageList.getSelectedRow(), 0).toString());
    }

    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void showListGV(List<Teacher> teachersList) {
        cbSelectedGV.removeAllItems();
        for (Teacher teacher : teachersList) {
            cbSelectedGV.addItem(teacher.getId() + " - " + teacher.getName());
        }

        //set selection for cbSelectedGV, searching data in courseTeacherMap
        for (CourseTeacherEntry entry : courseTeacherMap) {
            if (entry.getCourseId() == editingPackage) {
                for (Entry teacherEntry : entry.getTeacherMap()) {
                    if (teacherEntry.getIdMonhoc() == getSelectedSubject()) {
                        String teacherName = "";
                        for (Teacher teacher : teachersList) {
                            if (teacher.getId() == teacherEntry.getIdTeacher()) {
                                teacherName = teacher.getName();
                                break;
                            }
                        }
                        cbSelectedGV.setSelectedItem(teacherEntry.getIdTeacher() + " - " + teacherName);
                        break;
                    }
                }
            }
        }

    }

    public void showListMonhoc(int id)
    {
        editingPackage = id;
        for (CourseTeacherEntry entry : courseTeacherMap) {
            if (entry.getCourseId() == id) {
                showSubjects(entry.getTeacherMap());
                break;
            }
        }
    }
     
    public int getSelectedSubject()
    {
        return Integer.parseInt(listMonhoc.getSelectedValue().toString().split(" - ")[0]);
    }

    

    public Student getStudentInfo() {
        if (!validateName() || !validateAddress())
            return null;
        try {

            Student student = new Student();
            if (FIDSearchStudentStep3.getText() != null && !"".equals(FIDSearchStudentStep3.getText())) {
                student.setId(Integer.parseInt(FIDSearchStudentStep3.getText()));
            }

            student.setName(FNameSearchStudentStep3.getText());

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            student.setDate(dateFormat.format(FDateSearchStudentStep3.getDate()));

            if (chkMStep3.isSelected() == true)
                student.setGioitinh("Nam");
            else
                student.setGioitinh("Nữ");

            student.setAddress(FAddressSearchStudentStep3.getText());
            student.setLop(editingLop);

            /*
             * Map<Integer, Boolean> courseFeeMap = new HashMap<>();
             * List<CourseFeeEntry> courseFeeEntries = new ArrayList<>();
             * 
             * DefaultTableModel model = (DefaultTableModel) tbPackageList.getModel();
             * int rowCount = model.getRowCount();
             * for (int i = 0; i < rowCount; i++) {
             * int id = (int) model.getValueAt(i, 0);
             * boolean fee = (boolean) model.getValueAt(i, 2);
             * courseFeeMap.put(id, fee);
             * 
             * // Create a CourseFeeEntry for each row and add it to the list
             * CourseFeeEntry entry = new CourseFeeEntry();
             * entry.setCourseId(id);
             * entry.setFee(fee);
             * courseFeeEntries.add(entry);
             * }
             * 
             * student.setCourseFeeMap(courseFeeEntries);
             */
            student.setCourseTeacherMap(courseTeacherMap);

            return student;
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return null;

    }

//    public void clearStudentInfo()
//    {
//        FIDSearchStudentStep3.setText("");
//        FNameSearchStudentStep3.setText("");
//        
//        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
//
//        try {
//            // Chuyển đổi chuỗi thành đối tượng Date
//            Date date = dateFormat.parse("01/01/2024");
//
//            // Thiết lập ngày cho JDateChooser
//            FDateSearchStudentStep3.setDate(date);
//        } catch (ParseException e) {
//            e.printStackTrace();
//        }
        
//        chkMStep3.setSelected(true);
//        FAddressSearchStudentStep3.setText("");
//        DefaultTableModel model = (DefaultTableModel) tbPackageList.getModel();
//        model.setRowCount(0);
//        DefaultListModel<String> listModel = new DefaultListModel<>();
//        listMonhoc.setModel(listModel);
//        FNameSearchStudentStep3.setEnabled(true);
//        FDateSearchStudentStep3.setEnabled(true);
//        chkMStep3.setEnabled(true);
//        chkFStep3.setEnabled(true);
//        FAddressSearchStudentStep3.setEnabled(true);
//        BtnAddStudent.setEnabled(true);
//        
//    }

    private boolean validateName() {
        String name = FNameSearchStudentStep3.getText();
        if (name == null || name.isEmpty()) {
            FNameSearchStudentStep3.requestFocus();
            showMessage("Tên không được để trống");
            return false;
        }
        return true;
    }

    private boolean validateAddress() {
        String address = FAddressSearchStudentStep3.getText();
        if (address == null || address.isEmpty()) {
            FAddressSearchStudentStep3.requestFocus();
            showMessage("Quê quán không được để trống");
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddStudent;
    private javax.swing.JButton BtnAddStudent1;
    private javax.swing.JTextField FAddressSearchStudentStep4;
    private com.toedter.calendar.JDateChooser FDateSearchStudentStep4;
    private javax.swing.JTextField FIDSearchStudentStep4;
    private javax.swing.JTextField FNameSearchStudentStep4;
    private javax.swing.JLayeredPane Step1;
    private javax.swing.JLayeredPane Step2;
    private javax.swing.JLayeredPane Step3;
    private javax.swing.JLayeredPane Step4;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnGVSave;
    private javax.swing.JButton btnGVSave1;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnPull;
    private javax.swing.JButton btnPush;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbSelectedGV;
    private javax.swing.JComboBox<String> cbSelectedGV1;
    private javax.swing.JCheckBox chkFStep4;
    private javax.swing.JCheckBox chkMStep4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JList<String> listChoose;
    private javax.swing.JList<String> listInv;
    private javax.swing.JList<String> listMonhoc;
    private javax.swing.JList<String> listMonhoc1;
    private javax.swing.JTable tbPackageList;
    private javax.swing.JTable tbPackageList1;
    private javax.swing.JTable tbPackageListStep2;
    // End of variables declaration//GEN-END:variables
}
