/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.tad_sebs.View;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import vn.tad_sebs.Model.Department;
import vn.tad_sebs.Model.Lanhdao;
import vn.tad_sebs.Model.Teacher;

/**
 *
 * @author ASUS
 */
public class TeacherView extends javax.swing.JFrame {

    /**
     * Creates new form TeacherView
     */
    public TeacherView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnDeleteStudent = new javax.swing.JButton();
        FClassSearchStudent = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnEditStudent = new javax.swing.JButton();
        FSexStudent = new javax.swing.JTextField();
        BtnAddStudent = new javax.swing.JButton();
        BtnClearStudent = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        FAddressSearchStudent = new javax.swing.JTextField();
        FNameSearchStudent = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FDateSearchStudent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FIDSearchStudent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FTeacherSearchStudent = new javax.swing.JTextField();
        FScoreSearchStudent = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LDtable = new javax.swing.JTable();
        CbbSeacrchLD = new javax.swing.JComboBox<>();
        FSearchLD = new javax.swing.JTextField();
        btnSearchLD = new javax.swing.JButton();
        btnSortbyidLD = new javax.swing.JButton();
        btnSortbyNameLD = new javax.swing.JButton();
        btnSortbyLevelLD = new javax.swing.JButton();
        btnEditLD = new javax.swing.JButton();
        FNameSearchLD = new javax.swing.JTextField();
        FAddressSearchLD = new javax.swing.JTextField();
        btnAddLD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FLevelSearchLD = new javax.swing.JTextField();
        FRoleSearchLD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnClearLD = new javax.swing.JButton();
        FIDSearchLD = new javax.swing.JTextField();
        btnDeleteLD = new javax.swing.JButton();
        btnSortbyRole = new javax.swing.JButton();
        FDateSearchLD = new com.toedter.calendar.JDateChooser();
        CbMLD = new javax.swing.JCheckBox();
        CbFLD = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GVtable = new javax.swing.JTable();
        FLevelSearchGV = new javax.swing.JTextField();
        FAddressSearchGV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSortbyidGV = new javax.swing.JButton();
        FRoleSearchGV = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnAddGV = new javax.swing.JButton();
        btnEditGV = new javax.swing.JButton();
        CbbSeacrchGV = new javax.swing.JComboBox<>();
        FNameSearchGV = new javax.swing.JTextField();
        btnSearchGV = new javax.swing.JButton();
        btnSortbyNameGV = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnSortbyLevelGV = new javax.swing.JButton();
        FSearchGV = new javax.swing.JTextField();
        FIDSearchGV = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnClearGV = new javax.swing.JButton();
        btnDeleteGV = new javax.swing.JButton();
        FClassSearchGV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        cbDpChoose = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        cbDpEdit = new javax.swing.JComboBox<>();
        FDateSearchGV = new com.toedter.calendar.JDateChooser();
        CbMGV = new javax.swing.JCheckBox();
        CbFGV = new javax.swing.JCheckBox();

        BtnDeleteStudent.setText("Xóa");
        BtnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteStudentActionPerformed(evt);
            }
        });

        jLabel7.setText("Lớp");

        jLabel4.setText("Ngày sinh");

        BtnEditStudent.setText("Chỉnh sửa");
        BtnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditStudentActionPerformed(evt);
            }
        });

        BtnAddStudent.setText("Thêm");

        BtnClearStudent.setText("Clear");

        jLabel12.setText("Họ và tên");

        FAddressSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAddressSearchStudentActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel6.setText("Quê quán");

        jLabel9.setText("Điểm");

        FIDSearchStudent.setEnabled(false);
        FIDSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDSearchStudentActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tính");

        FTeacherSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTeacherSearchStudentActionPerformed(evt);
            }
        });

        jLabel17.setText("GVCN");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LDtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Họ và tên", "Ngày sinh", "Giới tính", "Quê quán", "Cấp bậc hàm", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(LDtable);

        CbbSeacrchLD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên", "Quê quán", "Giới tính", "Cấp bậc hàm" }));

        btnSearchLD.setText("Tìm");
        btnSearchLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchLDActionPerformed(evt);
            }
        });

        btnSortbyidLD.setText("Sắp xếp theo ID");

        btnSortbyNameLD.setText("Sắp xếp theo tên");

        btnSortbyLevelLD.setText("Sắp xếp theo Cấp bậc hàm");

        btnEditLD.setText("Chỉnh sửa");
        btnEditLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLDActionPerformed(evt);
            }
        });

        FAddressSearchLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAddressSearchLDActionPerformed(evt);
            }
        });

        btnAddLD.setText("Thêm");
        btnAddLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLDActionPerformed(evt);
            }
        });

        jLabel3.setText("ID");

        jLabel8.setText("Ngày sinh");

        jLabel10.setText("Giới tính");

        jLabel11.setText("Quê quán");

        FRoleSearchLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRoleSearchLDActionPerformed(evt);
            }
        });

        jLabel13.setText("Cấp bậc hàm");

        jLabel15.setText("Họ và tên");

        jLabel18.setText("Chức vụ");

        btnClearLD.setText("Clear");

        FIDSearchLD.setEnabled(false);
        FIDSearchLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDSearchLDActionPerformed(evt);
            }
        });

        btnDeleteLD.setText("Xóa");
        btnDeleteLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteLDActionPerformed(evt);
            }
        });

        btnSortbyRole.setText("Sắp xếp theo Chức vụ");

        FDateSearchLD.setDateFormatString("dd/MM/yyyy");

        buttonGroup2.add(CbMLD);
        CbMLD.setText("Nam");

        buttonGroup2.add(CbFLD);
        CbFLD.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FRoleSearchLD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FLevelSearchLD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FAddressSearchLD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FIDSearchLD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FNameSearchLD, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(FDateSearchLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CbMLD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CbFLD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteLD, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddLD, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditLD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(btnClearLD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(CbbSeacrchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchLD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnSortbyidLD)
                                .addGap(18, 18, 18)
                                .addComponent(btnSortbyNameLD)
                                .addGap(18, 18, 18)
                                .addComponent(btnSortbyLevelLD)
                                .addGap(18, 18, 18)
                                .addComponent(btnSortbyRole)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbbSeacrchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchLD))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FIDSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(FNameSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(FDateSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(CbMLD)
                            .addComponent(CbFLD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FAddressSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FLevelSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FRoleSearchLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteLD)
                            .addComponent(btnAddLD)
                            .addComponent(btnEditLD)
                            .addComponent(btnClearLD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortbyNameLD)
                    .addComponent(btnSortbyidLD)
                    .addComponent(btnSortbyLevelLD)
                    .addComponent(btnSortbyRole))
                .addGap(44, 44, 44))
        );

        jTabbedPane4.addTab("Lãnh đạo", jPanel1);

        GVtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "Ngày sinh", "Giới tính", "Quê quán", "Cấp bậc hàm", "Môn giảng dạy", "Lớp phụ trách", "Phòng ban"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(GVtable);

        FAddressSearchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAddressSearchGVActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        jLabel16.setText("Ngày sinh");

        btnSortbyidGV.setText("Sắp xếp theo ID");

        FRoleSearchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FRoleSearchGVActionPerformed(evt);
            }
        });

        jLabel19.setText("Họ và tên");

        jLabel20.setText("Cấp bậc hàm");

        jLabel21.setText("Giới tính");

        btnAddGV.setText("Thêm");

        btnEditGV.setText("Chỉnh sửa");
        btnEditGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditGVActionPerformed(evt);
            }
        });

        CbbSeacrchGV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tên", "Quê quán", "Giới tính", "Cấp bậc hàm", "Môn giảng dạy", "Lớp phụ trách" }));
        CbbSeacrchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbbSeacrchGVActionPerformed(evt);
            }
        });

        btnSearchGV.setText("Tìm");
        btnSearchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchGVActionPerformed(evt);
            }
        });

        btnSortbyNameGV.setText("Sắp xếp theo tên");

        jLabel22.setText("Quê quán");

        btnSortbyLevelGV.setText("Sắp xếp theo Cấp bậc hàm");

        FIDSearchGV.setEnabled(false);
        FIDSearchGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIDSearchGVActionPerformed(evt);
            }
        });

        jLabel23.setText("Môn giảng dạy");

        btnClearGV.setText("Clear");

        btnDeleteGV.setText("Xóa");
        btnDeleteGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGVActionPerformed(evt);
            }
        });

        jLabel1.setText("Lớp phụ trách");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("Chọn phòng ban:");

        cbDpChoose.setToolTipText("");
        cbDpChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDpChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(cbDpChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(cbDpChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLabel25.setText("Phòng ban");

        FDateSearchGV.setDateFormatString("dd/MM/yyyy");

        buttonGroup1.add(CbMGV);
        CbMGV.setText("Nam");

        buttonGroup1.add(CbFGV);
        CbFGV.setText("Nữ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSortbyidGV)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortbyNameGV)
                        .addGap(18, 18, 18)
                        .addComponent(btnSortbyLevelGV))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(CbbSeacrchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(FSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchGV)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FClassSearchGV)
                            .addComponent(FRoleSearchGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(FLevelSearchGV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FAddressSearchGV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FIDSearchGV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FNameSearchGV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbDpEdit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FDateSearchGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CbMGV, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbFGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDeleteGV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddGV, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditGV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearGV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbbSeacrchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchGV))
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(FIDSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(FNameSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(FDateSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(CbMGV)
                            .addComponent(CbFGV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FAddressSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FLevelSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FRoleSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FClassSearchGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(cbDpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteGV)
                            .addComponent(btnAddGV)
                            .addComponent(btnEditGV)
                            .addComponent(btnClearGV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortbyNameGV)
                    .addComponent(btnSortbyidGV)
                    .addComponent(btnSortbyLevelGV))
                .addGap(44, 44, 44))
        );

        jTabbedPane4.addTab("Giảng viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane4.getAccessibleContext().setAccessibleName("Lãnh đạo");

        setBounds(0, 0, 1515, 775);
    }// </editor-fold>//GEN-END:initComponents

    private void FTeacherSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTeacherSearchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FTeacherSearchStudentActionPerformed

    private void FAddressSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAddressSearchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAddressSearchStudentActionPerformed

    private void FIDSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDSearchStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDSearchStudentActionPerformed

    private void BtnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeleteStudentActionPerformed

    private void BtnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditStudentActionPerformed

    private void btnSearchLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchLDActionPerformed

    private void btnEditLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditLDActionPerformed

    private void FAddressSearchLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAddressSearchLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAddressSearchLDActionPerformed

    private void FRoleSearchLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRoleSearchLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRoleSearchLDActionPerformed

    private void FIDSearchLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDSearchLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDSearchLDActionPerformed

    private void btnDeleteLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteLDActionPerformed

    private void FAddressSearchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAddressSearchGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FAddressSearchGVActionPerformed

    private void FRoleSearchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FRoleSearchGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FRoleSearchGVActionPerformed

    private void btnEditGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditGVActionPerformed

    private void btnSearchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchGVActionPerformed

    private void FIDSearchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIDSearchGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIDSearchGVActionPerformed

    private void btnDeleteGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGVActionPerformed

    private void CbbSeacrchGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbbSeacrchGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbbSeacrchGVActionPerformed

    private void btnAddLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddLDActionPerformed

    private void cbDpChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDpChooseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDpChooseActionPerformed
    private String[] columnNamesGV = new String[] {
            "ID", "Họ và tên ", "Ngày sinh", "Giới tính", "Quê quán", "Cấp bậc hàm", "Môn giảng dạy", "Lớp phụ trách", "Phòng ban" };
    public void showListGV(List<Teacher> list) {
        int size = list.size();
        Object[][] teachers = new Object[size][9];
        for (int i = 0; i < size; i++) {
            teachers[i][0] = list.get(i).getId();
            teachers[i][1] = list.get(i).getName();
            teachers[i][2] = list.get(i).getDate();
            teachers[i][3] = list.get(i).getSex();
            teachers[i][4] = list.get(i).getAddress();
            teachers[i][5] = list.get(i).getCapbacham();
            teachers[i][6] = list.get(i).getMon();
            teachers[i][7] = list.get(i).getLop();
            teachers[i][8] = list.get(i).getDp();
        }
        GVtable.setModel(new DefaultTableModel(teachers, columnNamesGV));
    }
    public void fillGVFromSelectedRow() {
        // lấy chỉ số của hàng được chọn
        int row = GVtable.getSelectedRow();
        if (row >= 0) {
            FIDSearchGV.setText(GVtable.getModel().getValueAt(row, 0).toString());
            FNameSearchGV.setText(GVtable.getModel().getValueAt(row, 1).toString());
            String dateString = GVtable.getModel().getValueAt(row, 2).toString(); 
            // Chuỗi ngày tháng cần chuyển đổi
            JDateChooser dateChooser = new JDateChooser();

            // Định dạng của chuỗi ngày tháng
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            try {
                // Chuyển đổi chuỗi thành đối tượng Date
                Date date = dateFormat.parse(dateString);

                // Thiết lập ngày cho JDateChooser
                FDateSearchGV.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            if ("Nam".equals(GVtable.getModel().getValueAt(row, 3).toString())) {
                CbMGV.setSelected(true);
            } else
                CbFGV.setSelected(true);
            FAddressSearchGV.setText(GVtable.getModel().getValueAt(row, 4).toString());
            FLevelSearchGV.setText(GVtable.getModel().getValueAt(row, 5).toString());
            FRoleSearchGV.setText(GVtable.getModel().getValueAt(row, 6).toString());
            FClassSearchGV.setText(GVtable.getModel().getValueAt(row, 7).toString());
            cbDpEdit.setSelectedIndex(Integer.parseInt(GVtable.getModel().getValueAt(row, 8).toString())-1);
            // enable Edit and Delete buttons
            btnEditGV.setEnabled(true);
            btnDeleteGV.setEnabled(true);
            // disable Add button
            btnAddGV.setEnabled(false);
        }
    }
    public void showGV(Teacher teacher)
    {
        FIDSearchGV.setText(String.valueOf(teacher.getId()));
        FNameSearchGV.setText(teacher.getName());
         String dateString = teacher.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);

            // Thiết lập ngày cho JDateChooser
            FDateSearchGV.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        if (teacher.getSex() == "Nam") {
            CbMGV.setSelected(true);
        } else
            CbFGV.setSelected(true);
        FAddressSearchGV.setText(teacher.getAddress());
        FLevelSearchGV.setText(teacher.getCapbacham());
        FRoleSearchGV.setText(teacher.getMon());
        FClassSearchGV.setText(String.valueOf(teacher.getLop()));
        cbDpEdit.setSelectedIndex(teacher.getDp()-1);
        //enable Delete and edit button
        btnEditGV.setEnabled(true);
        btnDeleteGV.setEnabled(true);
        //disable Add button
        btnAddGV.setEnabled(false);
    }
    public void clearGVInfo() {
        FIDSearchGV.setText("");
        FNameSearchGV.setText("");
        String dateString = "01/01/2024"; // Chuỗi ngày tháng cần chuyển đổi
        JDateChooser dateChooser = new JDateChooser();

        // Định dạng của chuỗi ngày tháng
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);

            // Thiết lập ngày cho JDateChooser
            FDateSearchGV.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        CbMGV.setSelected(true);
        FAddressSearchGV.setText("");
        FClassSearchGV.setText("");
        FLevelSearchGV.setText("");
        FRoleSearchGV.setText("");
        cbDpEdit.setSelectedIndex(0);
        // disable Edit and Delete buttons
        btnEditGV.setEnabled(false);
        btnDeleteGV.setEnabled(false);
        // enable Add button
        btnAddGV.setEnabled(true);
    }
     public String getSelectedTextGV() {
        return CbbSeacrchGV.getSelectedItem().toString();
    }
    
    public String getSearchBoxGV()
    {
        return FSearchGV.getText().trim();
    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void addAddGVListener(ActionListener listener) {
        btnAddGV.addActionListener(listener);
    }
    public Teacher getGVInfo()
    {
        try
        {
            
            Teacher teacher = new Teacher();
            if(FIDSearchGV.getText()!=null && !"".equals(FIDSearchGV.getText()))
            {
                teacher.setId(Integer.parseInt(FIDSearchGV.getText()));
            }

            teacher.setName(FNameSearchGV.getText());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            teacher.setDate(dateFormat.format(FDateSearchGV.getDate()));

            if(CbMGV.isSelected() == true)
                teacher.setSex("Nam");
            else
                teacher.setSex("Nữ");
            teacher.setAddress(FAddressSearchGV.getText());
            teacher.setCapbacham(FLevelSearchGV.getText());
            teacher.setMon(FRoleSearchGV.getText());
            teacher.setLop(FClassSearchGV.getText());
            teacher.setDp(cbDpEdit.getSelectedIndex() + 1);
            return teacher;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
        
    }
    public void addEditGVListener(ActionListener listener) {
        btnEditGV.addActionListener(listener);
    }

    public void addDeleteGVListener(ActionListener listener) {
        btnDeleteGV.addActionListener(listener);
    }

    public void addClearGVListener(ActionListener listener) {
        btnClearGV.addActionListener(listener);
    }

    public void addListGVSelectionListener(ListSelectionListener listener) {
        GVtable.getSelectionModel().addListSelectionListener(listener);
    }

    public void addSearchGVListener(ActionListener listener) {
        btnSearchGV.addActionListener(listener);
    }
    public void addSortGVByIDListener(ActionListener listener)
    {
        btnSortbyidGV.addActionListener(listener);
    }
    public void addSortGVByNameListener(ActionListener listener)
    {
        btnSortbyNameGV.addActionListener(listener);
    }
      public void addSortGVByLevelListener(ActionListener listener)
    {
        btnSortbyLevelGV.addActionListener(listener);
    }
    public void addListDPSelectionListener(ActionListener listener)
    {
        cbDpChoose.addActionListener(listener);
    }

    public void showListDP(List<Department> list)
    {
        int size = list.size();
        Object[][] departments = new Object[size][3];
        for (int i = 0; i < size; i++) {
            cbDpChoose.addItem(list.get(i).getId() + " - " + list.get(i).getName());
            cbDpEdit.addItem(list.get(i).getId() + " - " + list.get(i).getName());
        }
    }
    public int getDPChoice()
    {
        return cbDpChoose.getSelectedIndex() + 1;
    }
    // ----- Lanh Dao

    private String[] columnNamesLD = new String[] { 
            "ID", "Họ và tên ", "Ngày sinh", "Giới tính", "Quê quán", "Cấp bậc hàm", "Chức vụ" };
    public void showListLD(List<Lanhdao> list) {
        int size = list.size();
        Object[][] lanhdao = new Object[size][7];
        for (int i = 0; i < size; i++) {
            lanhdao[i][0] = list.get(i).getId();
            lanhdao[i][1] = list.get(i).getName();
            lanhdao[i][2] = list.get(i).getDate();
            lanhdao[i][3] = list.get(i).getSex();
            lanhdao[i][4] = list.get(i).getAddress();
            lanhdao[i][5] = list.get(i).getCapbacham();
            lanhdao[i][6] = list.get(i).getChucvu();
        }
        LDtable.setModel(new DefaultTableModel(lanhdao, columnNamesLD));
    }
    public void fillLDFromSelectedRow() {
        // lấy chỉ số của hàng được chọn
        int row = LDtable.getSelectedRow();
        if (row >= 0) {
            FIDSearchLD.setText(LDtable.getModel().getValueAt(row, 0).toString());
            FNameSearchLD.setText(LDtable.getModel().getValueAt(row, 1).toString());
             String dateString = LDtable.getModel().getValueAt(row, 2).toString(); 
            // Chuỗi ngày tháng cần chuyển đổi
            JDateChooser dateChooser = new JDateChooser();

            // Định dạng của chuỗi ngày tháng
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

            try {
                // Chuyển đổi chuỗi thành đối tượng Date
                Date date = dateFormat.parse(dateString);

                // Thiết lập ngày cho JDateChooser
                FDateSearchLD.setDate(date);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            if ("Nam".equals(LDtable.getModel().getValueAt(row, 3).toString())) {
                CbMLD.setSelected(true);
            } else
                CbFLD.setSelected(true);
            FAddressSearchLD.setText(LDtable.getModel().getValueAt(row, 4).toString());
            FLevelSearchLD.setText(LDtable.getModel().getValueAt(row, 5).toString());
            FRoleSearchLD.setText(LDtable.getModel().getValueAt(row, 6).toString());
            // enable Edit and Delete buttons
            btnEditLD.setEnabled(true);
            btnDeleteLD.setEnabled(true);
            // disable Add button
            btnAddLD.setEnabled(false);
        }
    }
    public void showLD(Lanhdao lanhdao)
    {
        FIDSearchLD.setText(String.valueOf(lanhdao.getId()));
        FNameSearchLD.setText(lanhdao.getName());
        String dateString = lanhdao.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);

            // Thiết lập ngày cho JDateChooser
            FDateSearchLD.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        if (lanhdao.getSex() == "Nam") {
            CbMLD.setSelected(true);
        } else
            CbFLD.setSelected(true);
        FAddressSearchLD.setText(lanhdao.getAddress());
        FLevelSearchLD.setText(lanhdao.getCapbacham());
        FRoleSearchLD.setText(lanhdao.getChucvu());
        //enable Delete and edit button
        btnEditLD.setEnabled(true);
        btnDeleteLD.setEnabled(true);
        //disable Add button
        btnAddLD.setEnabled(false);
    }
    public void clearLDInfo() {
        FIDSearchLD.setText("");
        FNameSearchLD.setText("");
        String dateString = "01/01/2024"; // Chuỗi ngày tháng cần chuyển đổi
        JDateChooser dateChooser = new JDateChooser();

        // Định dạng của chuỗi ngày tháng
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            // Chuyển đổi chuỗi thành đối tượng Date
            Date date = dateFormat.parse(dateString);

            // Thiết lập ngày cho JDateChooser
            FDateSearchLD.setDate(date);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        CbMLD.setSelected(true);
        FAddressSearchLD.setText("");
        FLevelSearchLD.setText("");
        FRoleSearchLD.setText("");
        // disable Edit and Delete buttons
        btnEditLD.setEnabled(false);
        btnDeleteLD.setEnabled(false);
        // enable Add button
        btnAddLD.setEnabled(true);
    }
     public String getSelectedTextLD() {
        return CbbSeacrchLD.getSelectedItem().toString();
    }
    
    public String getSearchBoxLD()
    {
        return FSearchLD.getText().trim();
    }
     public void addAddLDListener(ActionListener listener) {
        btnAddLD.addActionListener(listener);
    }
    public Lanhdao getLDInfo()
    {
        try
        {
            
            Lanhdao lanhdao = new Lanhdao();
            if(FIDSearchLD.getText()!=null && !"".equals(FIDSearchLD.getText()))
            {
                lanhdao.setId(Integer.parseInt(FIDSearchLD.getText()));
            }

            lanhdao.setName(FNameSearchLD.getText());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            lanhdao.setDate(dateFormat.format(FDateSearchLD.getDate()));

            if(CbMLD.isSelected() == true)
                lanhdao.setSex("Nam");
            else
                lanhdao.setSex("Nữ");
            lanhdao.setAddress(FAddressSearchLD.getText());
            lanhdao.setCapbacham(FLevelSearchLD.getText());
            lanhdao.setChucvu(FRoleSearchLD.getText());
            return lanhdao;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
        
    }
    public void addEditLDListener(ActionListener listener) {
        btnEditLD.addActionListener(listener);
    }

    public void addDeleteLDListener(ActionListener listener) {
        btnDeleteLD.addActionListener(listener);
    }

    public void addClearLDListener(ActionListener listener) {
        btnClearLD.addActionListener(listener);
    }

    public void addListLDSelectionListener(ListSelectionListener listener) {
        LDtable.getSelectionModel().addListSelectionListener(listener);
    }

    public void addSearchLDListener(ActionListener listener) {
        btnSearchLD.addActionListener(listener);
    }
    public void addSortLDByIDListener(ActionListener listener)
    {
        btnSortbyidLD.addActionListener(listener);
    }
    public void addSortLDByNameListener(ActionListener listener)
    {
        btnSortbyNameLD.addActionListener(listener);
    }
    public void addSortLDByLevelListener(ActionListener listener)
    {
        btnSortbyLevelLD.addActionListener(listener);
    }
    public void addSortLDByRoleListener(ActionListener listener)
    {
        btnSortbyRole.addActionListener(listener);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddStudent;
    private javax.swing.JButton BtnClearStudent;
    private javax.swing.JButton BtnDeleteStudent;
    private javax.swing.JButton BtnEditStudent;
    private javax.swing.JCheckBox CbFGV;
    private javax.swing.JCheckBox CbFLD;
    private javax.swing.JCheckBox CbMGV;
    private javax.swing.JCheckBox CbMLD;
    private javax.swing.JComboBox<String> CbbSeacrchGV;
    private javax.swing.JComboBox<String> CbbSeacrchLD;
    private javax.swing.JTextField FAddressSearchGV;
    private javax.swing.JTextField FAddressSearchLD;
    private javax.swing.JTextField FAddressSearchStudent;
    private javax.swing.JTextField FClassSearchGV;
    private javax.swing.JTextField FClassSearchStudent;
    private com.toedter.calendar.JDateChooser FDateSearchGV;
    private com.toedter.calendar.JDateChooser FDateSearchLD;
    private javax.swing.JTextField FDateSearchStudent;
    private javax.swing.JTextField FIDSearchGV;
    private javax.swing.JTextField FIDSearchLD;
    private javax.swing.JTextField FIDSearchStudent;
    private javax.swing.JTextField FLevelSearchGV;
    private javax.swing.JTextField FLevelSearchLD;
    private javax.swing.JTextField FNameSearchGV;
    private javax.swing.JTextField FNameSearchLD;
    private javax.swing.JTextField FNameSearchStudent;
    private javax.swing.JTextField FRoleSearchGV;
    private javax.swing.JTextField FRoleSearchLD;
    private javax.swing.JTextField FScoreSearchStudent;
    private javax.swing.JTextField FSearchGV;
    private javax.swing.JTextField FSearchLD;
    private javax.swing.JTextField FSexStudent;
    private javax.swing.JTextField FTeacherSearchStudent;
    private javax.swing.JTable GVtable;
    private javax.swing.JTable LDtable;
    private javax.swing.JButton btnAddGV;
    private javax.swing.JButton btnAddLD;
    private javax.swing.JButton btnClearGV;
    private javax.swing.JButton btnClearLD;
    private javax.swing.JButton btnDeleteGV;
    private javax.swing.JButton btnDeleteLD;
    private javax.swing.JButton btnEditGV;
    private javax.swing.JButton btnEditLD;
    private javax.swing.JButton btnSearchGV;
    private javax.swing.JButton btnSearchLD;
    private javax.swing.JButton btnSortbyLevelGV;
    private javax.swing.JButton btnSortbyLevelLD;
    private javax.swing.JButton btnSortbyNameGV;
    private javax.swing.JButton btnSortbyNameLD;
    private javax.swing.JButton btnSortbyRole;
    private javax.swing.JButton btnSortbyidGV;
    private javax.swing.JButton btnSortbyidLD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbDpChoose;
    private javax.swing.JComboBox<String> cbDpEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
